### ISSUE TITLE
Boilerplate code in sql_queries.py is incorrect

### ISSUE THREAD

**Issue by mlgvla** [learn-co-curriculum/python-p3-organizing-bears-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204250?module_item_id=468012

### Concern

selects_all_female_bears_return_name_and_age = """
    Write your SQL query here
"""

selects_all_bears_names_and_orders_in_alphabetical_order = """
    Write your SQL query here
"""

selects_all_bears_names_and_ages_that_are_alive_and_order_youngest_to_oldest = """
    Write your SQL query here
"""

selects_oldest_bear_and_returns_name_and_age = """
    Write your SQL query here
"""
select_youngest_bear_and_returns_name_and_age = """
    Write your SQL query here
"""

### Suggested Changes

All the "selects_"... need to be "select_..." in order to pass the tests.

**Comment by professor-ben** [comment]
Just fixed this- thanks for the report!
