### ISSUE TITLE
Test is not being output in the terminal after running pytest

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/python-p3-organizing-bears-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204250?module_item_id=468012

### Concern

Student is asked to write a sql query called select_all_bears_names_and_ages_that_are_alive_and_order_youngest_to_oldest 
The test is in the test file as well but when pytest is run nothing is output to the terminal in regards to that specific test. Looking at the test, it is unclear why that is happening. Attached is a screenshot, which includes the test for the query and the terminal output when pytest is run. May be confusing for students.

<img width="1105" alt="Screen Shot 2023-01-22 at 2 01 01 PM" src="https://user-images.githubusercontent.com/81705554/213934773-6c913c8a-75de-4332-91ad-aaf21c0a0b1b.png">

**Comment by professor-ben** [comment]
That's a headscratcher. I'll take a look at this now.
